"use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {EventsProvider, useEvents} from "./contexts/EventContext"
import {LoginProvider} from './contexts/LoginContext'
import {ClubProvider} from './contexts/ClubContext'


const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EventsProvider>
          <LoginProvider>
            <ClubProvider>
            {children}
           </ClubProvider>
          </LoginProvider>
        </EventsProvider>
      </body>
    </html>
  );
}
