version: '3.9'

services:
  frontend:
    build:
      context: ./frontend/teamxfrontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/teamxfrontend/.next:/app/.next
      - ./frontend/teamxfrontend:/app/src

  backend: # no exposed ports necessary here
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
      